In [69]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
%matplotlib inline

In [70]:
COLUMNS = ['class', 'age','menopause','tumor-size',
           'inv-nodes','node-caps','deg-malig','breast','breast-quad',
           'irradiat']
# read and store our data
df = pd.read_csv('breast_cancer.data', names=COLUMNS)
# print some item of dataframe
df.head()

,class,age,menopause,tumor-size,inv-nodes,node-caps,deg-malig,breast,breast-quad,irradiat
0,no-recurrence-events,30-39,premeno,30-34,0-2,no,3,left,left_low,no
1,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,right,right_up,no
2,no-recurrence-events,40-49,premeno,20-24,0-2,no,2,left,left_low,no
3,no-recurrence-events,60-69,ge40,15-19,0-2,no,2,right,left_up,no
4,no-recurrence-events,40-49,premeno,0-4,0-2,no,2,right,right_low,no

In [71]:
df.drop(['menopause', 'inv-nodes', 'breast'], axis=1, inplace=True)

In [72]:
df.head()

,class,age,tumor-size,node-caps,deg-malig,breast-quad,irradiat
0,no-recurrence-events,30-39,30-34,no,3,left_low,no
1,no-recurrence-events,40-49,20-24,no,2,right_up,no
2,no-recurrence-events,40-49,20-24,no,2,left_low,no
3,no-recurrence-events,60-69,15-19,no,2,left_up,no
4,no-recurrence-events,40-49,0-4,no,2,right_low,no

In [85]:
class_maps ={
    "no-recurrence-events":0,
    "recurrence-events":1
}
age_maps ={
    '10-19':0,
    '20-29':1,
    '30-39':2,
    '40-49':3,
    '50-59':4,
    '60-69':5,
    '70-79':6,
    '80-89':7,
    '90-99':8
}
tumor_maps ={
    '0-4':0,
    '5-9':1,
    '10-14':2,
    '15-19':3,
    '20-24':4,
    '25-29':5,
    '30-34':6,
    '35-39':7,
    '40-44':8,
    '45-49':9,
    '50-54':11,
    '55-59':12
}
node_maps = {
    '0-20':0,
    '21-39':1
}

quad_maps = {'left-up':0,"left-low":1,"right-up":2,"right-low":3,"central":4}

irradiat_maps ={
    "yes":0,
    "no":1
}

In [86]:
df["class"] = df["class"].map(class_maps)
df["age"] = df["age"].map(age_maps)
df["tumor-size"] = df["tumor-size"].map(tumor_maps)
df["node-caps"] = df["node-caps"].map(node_maps)
df["breast-quad"] = df["breast-quad"].map(quad_maps)
df["irradiat"] = df["irradiat"].map(irradiat_maps)

In [87]:
df.head()

   class  age  tumor-size  node-caps  deg-malig  breast-quad  irradiat
0      0    2           6        NaN          3          NaN         1
1      0    3           4        NaN          2          NaN         1
2      0    3           4        NaN          2          NaN         1
3      0    5           3        NaN          2          NaN         1
4      0    3           0        NaN          2          NaN         1

In [88]:
features = df.drop('irradiat', axis=1)

In [89]:
labels = df['irradiat']

In [90]:
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=.3)

In [91]:
from sklearn.linear_model import LogisticRegression

In [92]:
regressor = LogisticRegression()

In [93]:
regressor.fit(X_train, y_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').